Update github action

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -22,7 +22,18 @@ jobs:
       - name: Deploy to VPS
         run: |
           ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
+            if [ ! -d "~/gilang/kosan-api/.git" ]; then
+              echo "Repository not found. Cloning..."
+              git clone git@github.com:${{ github.repository }}.git ~/gilang/kosan-api
+            fi
+
             cd ~/gilang/kosan-api
             git pull origin master
+          
+            if [ ! -f "docker-compose.yml" ]; then
+              echo "Error: docker-compose.yml not found!"
+              exit 1
+            fi
+
             docker-compose up -d --build
           EOF
